apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job-8
  labels:
    app.kubernetes.io/instance: app-8
    tags.datadoghq.com/service: cron-job-8
spec:
  schedule: "0 5 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 100
      backoffLimit: 3
      ttlSecondsAfterFinished: 100
      template:
        metadata:
          labels:
            app: cron-job-8
        spec:
          restartPolicy: Never
          serviceAccountName: sa-app-8
          containers:
          - name: cron-job-8
            image: busybox:latest
            command: ["sh", "-c", "echo Running job 8 && sleep 10"]
            envFrom:
            - configMapRef:
                name: app-8-configmap
            - secretRef:
                name: app-8-secret
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 500Mi
