apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cronjob-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: app-1
        namespace: ns-app-1
      - name: app-2
        namespace: ns-app-2
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      destination:
        server: https://3715F7A0C3FA74C4A14DDE5FDA73D184.gr7.us-west-2.eks.amazonaws.com
        namespace: '{{namespace}}'
      source:
        repoURL: https://github.com/mmayman-amaz/argocd-repro-test.git
        targetRevision: HEAD
        path: apps/{{name}}/overlays/development
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
