apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd-custom
spec:
  project: default
  source:
    repoURL: https://github.com/mmayman-amaz/argocd-repro-test.git
    targetRevision: HEAD
    path: .
    directory:
      include: 'appset.yaml'
  destination:
    server: arn:aws:eks:us-west-2:165919938845:cluster/interesting-electro-ant-vessel-exercise
    namespace: argocd-custom
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
