apiVersion: batch/v1
kind: CronJob
metadata:
  name: base-cronjob
spec:
  schedule: "0 5 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 100
      backoffLimit: 3
      ttlSecondsAfterFinished: 100
      template:
        metadata:
          labels:
            app: base-cronjob
        spec:
          restartPolicy: Never
          serviceAccountName: sa-app
          containers:
          - name: job
            image: busybox:latest
            command: ["sh", "-c", "echo Running job && sleep 10"]
            envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secret
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 500Mi
