apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job-2
  labels:
    app.kubernetes.io/instance: app-2
    tags.datadoghq.com/service: cron-job-2
spec:
  schedule: "0 5 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 100
      backoffLimit: 3
      ttlSecondsAfterFinished: 100
      template:
        metadata:
          labels:
            app: cron-job-2
        spec:
          restartPolicy: Never
          serviceAccountName: sa-app-2
          containers:
          - name: cron-job-2
            image: busybox:latest
            command: ["sh", "-c", "echo Running job 2 && sleep 10"]
            envFrom:
            - configMapRef:
                name: app-2-configmap
            - secretRef:
                name: app-2-secret
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 500Mi
