apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/mmayman-amaz/argocd-repro-test//base/aws-java-job?ref=main
namePrefix: app-2-
commonLabels:
  app.kubernetes.io/instance: app-2
