apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-7-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake-store
    kind: ClusterSecretStore
  target:
    name: app-7-secret
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: /fake/secret
      property: password
  - secretKey: API_KEY
    remoteRef:
      key: /fake/secret
      property: username
